### ISSUE TITLE
hi, this workflow awesome but i try error env is not defined

### ISSUE THREAD

**Issue by mardianto** [ahmadHuss/groover-free-premium-ecommerce-template#1]
hi, this workflow awesome but i try error env is not defined,
please help how to fix setup env file?

thank you

**Comment by ahmadhuss** [comment]
Hi, @mardianto What do you mean? When you try to use `npm run dev` or `npm run build` command `env` error occurs. Can you provide more details on this issue or share a screenshot of your command-line tool? So that I can understand why this problem is appearing to you.

It is working fine on my side.
![example](https://user-images.githubusercontent.com/15076149/114310206-75e3c280-9b03-11eb-825a-6e32e337aa95.jpg)

Make sure first install all dependencies with `npm install` command.
